name: quiz_class_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  provider: ^6.0.5



dev_dependencies:
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_app.png"
  adaptive_icon_background: "#2575FC" # Warna background untuk Android
  adaptive_icon_foreground: "assets/images/icon_app.png" # Gambar foreground untuk Android

flutter_native_splash:
  color: "#2575FC" # Warna background splash
  image: "assets/images/icon_app.png" # Logo yang muncul di tengah
  android_12:
    image: "assets/images/icon_app.png"
    color: "#2575FC"
fullscreen: true

flutter:
  uses-material-design: true
